### ISSUE TITLE
Discord's character limit preventing found domains from printing correctly

### ISSUE THREAD

**Issue by 0x0luke** [Edu4rdSHL/findomain#101]
Discord's character limit on messages prevents the Discord webhook function from functioning correctly, creating malformed messages. Pseudo patch: Cut all text after 2000 characters/the character limit and append it to a new message? 

This might also be present on the Slack and Telegram implementations of the webhook features.

**Comment by Edu4rdSHL** [comment]
Hello, we currently cut all text according to webhooks character limits as you can see here https://github.com/Edu4rdSHL/findomain/blob/af38eaba114de76bb0c03737d2ce20363903b148/src/misc.rs#L75-L150 but we only send the first part of the message because if we start sending all the messages for targets that are really long (att for example) may ends in a IP blocking from the webhook side. Also currently that issue is not a problem since that we have email support with no-limit characters in our plus plans.

In resume: the problem is that if we send 200 messages for one target the webhook/api may block the user IP.
