### ISSUE TITLE
20. prefix for subdomains

### ISSUE THREAD

**Issue by spazbg** [Edu4rdSHL/findomain#114]
I think there is a problem with the parsing here, sometimes I get subdomains starting with 20. 

https://i.imgur.com/Zpe8luW.png

**Comment by Edu4rdSHL** [comment]
Hello, it isn't a parsing problem, it's a source sending crap in their JSON payload most likely Virustotal where anyone can put random URLs and them got indexed in the database. Las time was the "virus" word getting indexed in some subdomains:

![image](https://user-images.githubusercontent.com/32582878/90984689-2df43900-e53c-11ea-88c9-793872ad7fa2.png)

I can not do anything here because I can block subdomains starting with 20. but then last time they will be 10. and the problem will continue.

**Comment by spazbg** [comment]
Ok, thank you for the response.
PS: Great tool! 👍
