### ISSUE TITLE
Option for personalized output file name

### ISSUE THREAD

**Issue by j3ssie** [Edu4rdSHL/findomain#12]
Hi, findomain is really awesome tool. But I didn't any options to specify the filename of the output. Can you add an option for it?

It's default append `_<number>` to the target and that makes a little bit inconvenience for some automation workflow. Currently, I'm grepping ` >> ` from the stdout for that purpose :).

Best regards.

**Comment by Edu4rdSHL** [comment]
Hey @j3ssie, thank you for the feedback. The main reason why I just let the user to choose the format is because Findomain is capable of run the scan from a list of targets into a file. When it happens how can I fight with that if the user have 1000 domains, for example? The only option that I see is to let the use set that filename option when it uses the `-t` option that takes only a domain. Anyways I though that it's really not hard to automatize the job with the current model, see the following examples.

* To work directly with the output:

`findomain -t domain.com |cut -c 5- |httprobe`

You will get something similar to:

```
└─ ▶ findomain -t securityhacklabs.net |cut -c 5- |httprobe 
http://dvwa.securityhacklabs.net
http://blackarch.securityhacklabs.net
http://biblio.securityhacklabs.net
http://chat.securityhacklabs.net
http://art.securityhacklabs.net
http://correo.securityhacklabs.net
http://cpanel.securityhacklabs.net
snip...
```
To work with a file:

`findomain -t domain.com -o txt && cat domain.com_*.txt |httprobe`

You will get something similar to:

```
└─ ▶ findomain -t securityhacklabs.net -o txt && cat securityhacklabs.net_*.txt |httprobe 

Target ==> securityhacklabs.net

Searching in the CertSpotter API... 🔍
Searching in the Crtsh database... 🔍
Searching in the Sublist3r API... 🔍
Searching in the Spyse API... 🔍
Searching in the Bufferover API... 🔍
Searching in the Threadcrowd API... 🔍
Searching in the Virustotal API using apikey... 🔍
Searching in the Virustotal API... 🔍
Searching in the Facebook API... 🔍
An error ❌ has occurred while parsing the JSON obtained from the Threadcrowd API. Error description: JSON error.


A total of 50 subdomains were found for ==>  securityhacklabs.net 👽

 >> art.securityhacklabs.net
 >> autodiscover.securityhacklabs.net
 >> biblio.securityhacklabs.net
 >> blackarch.securityhacklabs.net
...snip
>> www.wpbackup.securityhacklabs.net

Good luck Hax0r 💀!

>> 📁 Filename for the target securityhacklabs.net was saved in: ./securityhacklabs.net_7083.txt 😀
http://dvwa.securityhacklabs.net
http://chat.securityhacklabs.net
http://correo.securityhacklabs.net
http://art.securityhacklabs.net
http://biblio.securityhacklabs.net
http://blackarch.securityhacklabs.net
http://cpanel.securityhacklabs.net
http://autodiscover.securityhacklabs.net
http://foro.securityhacklabs.net
...snip
```
Cheers.

**Comment by j3ssie** [comment]
Hi @Edu4rdSHL,

Yeah, I understand the purpose with that for scan from a list of targets into a file. But I think it will be better if we can specify the **postfix** for the output like `domain_postfix.txt` instead of a number.

Of course, we can do little hack with **httprobe** or **unfurl** but still need exactly output for other purposes.

Any really great tool.
Best regards,

**Comment by Edu4rdSHL** [comment]
Well, good idea. If I have understand correctly you shouls specify the $something.$format in the output. Like `findomain -t domain.com -o one.txt` and the output should be `domain.com_one.txt`?

**Comment by j3ssie** [comment]
Very nice simple but elegant :)

**Comment by Edu4rdSHL** [comment]
I'm working on it, @j3ssie. I will push to develop branch it weekend, will be good if you can do some testing.

**Comment by j3ssie** [comment]
Yeah, why not? Just commit a message on this issue I will testing for it :)

**Comment by Edu4rdSHL** [comment]
Hey @j3ssie. I have pushed a commit to the develop branch that will fix it issue definitively. Since that Findomain is capable of read N domains from a file it's a bit hard to just make the output file name a user choice when the -t option is used and not an user choice when reading domains from file. 

I have just put the output file name with the same name as the domain. For example, if you execute `findomain -t example.com -o`, the resulting output file name will be `example.com` and if that file already exists when findomain is executed, Findomain will wait for valid results and then overwrite the file.

Please check https://github.com/Edu4rdSHL/findomain/releases/tag/0.2.8-rc1 when you can.

**Comment by j3ssie** [comment]
Thank @Edu4rdSHL, It work like a charm 😍

**Comment by Edu4rdSHL** [comment]
Due to compatibility issues, I will add ".txt" format to all output files. The issue that I have found is that, for example in Windows a file with name `example.com` is interpreted as a `MS-DOS (.com) Application` and that may cause problems for users that want to read the results.
