### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by dzhenway** [Edu4rdSHL/findomain#16]
A total of 113 subdomains were found for ==>  xxx.target.com 👽

thread 'main' panicked at 'Failed to create file.: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by Edu4rdSHL** [comment]
Hello @dzhenway. That's happening because you're trying to write in a directory where you don't have permisions to write. Like that you are in `/etc` using your normal user and run Findomain there. Findomain try to write in current dir (`$PWD`) but doesnt' have permissions to write there.

Can you try changing the working directory to one where your current user have permissions to write? If not, then you need to run the tool as super user.
