### ISSUE TITLE
Error trying to connect

### ISSUE THREAD

**Issue by rd6r4gdk24w729h5bdaz** [Edu4rdSHL/findomain#6]
Hi,

Wanted to test your tool and got these errors:

root@2d9bdeceecc7:/opt# ./findomain-linux -V
findomain 0.2.1
root@2d9bdeceecc7:/opt# ./findomain-linux -a -t microsoft.com

Target ==> microsoft.com

Searching in the CertSpotter API... 🔍
An error ❌ as occured while procesing the request in the CertSpotter API. Error description: error trying to connect

Searching in the Crtsh API... 🔍
An error ❌ as occured while procesing the request in the Crtsh API. Error description: error trying to connect

Searching in the Virustotal API... 🔍
An error ❌ as occured while procesing the request in the Virustotal API. Error description: error trying to connect

Searching in the Sublist3r API... 🔍
An error ❌ as occured while procesing the request in the Sublist3r API. Error description: error trying to connect

Searching in the Facebook API... 🔍
An error ❌ as occured while procesing the request in the Facebook API. Error description: error trying to connect

**Comment by Edu4rdSHL** [comment]
Hello, @rd6r4gdk24w729h5bdaz thanks for reporting. Looks like that you're facing general connection issues.

Can you do something like `ping crt.sh` or `ping api.certspotter.com` and see what happens?

**Comment by rd6r4gdk24w729h5bdaz** [comment]
Here you are:
root@2d9bdeceecc7:/# ping api.certspotter.com 
PING certspotter.com (23.22.183.152) 56(84) bytes of data.
64 bytes from ec2-23-22-183-152.compute-1.amazonaws.com (23.22.183.152): icmp_seq=1 ttl=44 time=101 ms
64 bytes from ec2-23-22-183-152.compute-1.amazonaws.com (23.22.183.152): icmp_seq=2 ttl=44 time=102 ms
^C
--- certspotter.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 2ms
rtt min/avg/max/mdev = 101.329/101.545/101.762/0.385 ms
root@2d9bdeceecc7:/# ping crt.sh
PING crt.sh (91.199.212.48) 56(84) bytes of data.
64 bytes from crt.sh (91.199.212.48): icmp_seq=1 ttl=51 time=26.0 ms
64 bytes from crt.sh (91.199.212.48): icmp_seq=2 ttl=51 time=25.3 ms
^C
--- crt.sh ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 2ms
rtt min/avg/max/mdev = 25.336/25.676/26.016/0.340 ms
root@2d9bdeceecc7:/#

**Comment by Edu4rdSHL** [comment]
Thanks, that's a weird behavior because the "error trying to connect" message is caused when the API is unreachable and in it case all APIs are unreachable. Probably any firewall rule that's cutting the traffic from your PC to the APIs? Can you change your DNS's to 9.9.9.9 or 8.8.8.8 and try to execute the tool again?

**Comment by rd6r4gdk24w729h5bdaz** [comment]
I did some test and installed curl, git, net-tools and cargo.
I tried to compile using "cargo build --release" (it failed because of an error about openssl).
Anyway, after the failed compile attempt, the released binary you provided now works.
It looks like there is an undocumented dependency.

**Comment by Edu4rdSHL** [comment]
Thanks. Probably the build failed because `make` and/or `perl`

Looks like that I forget to add the same dependencies that I put [here](https://github.com/Edu4rdSHL/findomain#build-for-32-bits-or-another-platform) when [building from source in Linux](https://github.com/Edu4rdSHL/findomain#installation-in-linux-using-source-code).

I will add that dependencies now.
