### ISSUE TITLE
The AnubisDB API has failed returning the following HTTP status: 300 Multiple Choices

### ISSUE THREAD

**Issue by inj3ctor-m4** [Edu4rdSHL/findomain#67]
always when i start the tool this message came out from nowhere

**Comment by Edu4rdSHL** [comment]
It happens because the API doesn't return anything but still answer with a 200 HTTP code, so it's a API implementation issue and not a Findomain issue.

A lot of tools usually hide to the user what's happening and fails silently, I don't like it, I don't do it. If you want just use the quiet mode and all these messages will dissapear.
