### ISSUE TITLE
Remove alphanumeric from subdomains results

### ISSUE THREAD

**Issue by bugbaba** [Edu4rdSHL/findomain#69]
Hi,

while running findomain against `shopfiy.com` its finding one subdomain that starts with some non alphanumeric character.

you can reproduce/debug by running the below command and searching for `cdn.shopify.com`
```
./findomain -t shopfiy.com
```

![image](https://user-images.githubusercontent.com/29960776/75619948-ab9c4500-5ba8-11ea-8e1a-6e7c6e605308.png)

--
Regards,
@bugbaba

**Comment by sumgr0** [comment]
Handling the junk/non ascii characters in the output will be great.

**Comment by bugbaba** [comment]
junk values usually doesn't comes in subdomains enumeration, it just might be one of the sources or shopify might have setup things weirdly.

**Comment by Edu4rdSHL** [comment]
Hello, thanks for notifying the issue. It's an source issue more than an Findomain one, some API is sending junk in the JSON payload. Checking for non alphanumeric characters will not work because both `'ï','¼'` are alphanumeric characters. 

Findomain currently check if the subdomain contain some special characters in order to avoid it.

https://github.com/Edu4rdSHL/findomain/blob/be6ba4f3b30a9bdb0ed4e7d8e6e79a6095a10e0b/src/misc.rs#L9-L14

https://github.com/Edu4rdSHL/findomain/blob/be6ba4f3b30a9bdb0ed4e7d8e6e79a6095a10e0b/src/misc.rs#L212-L217

What I can do is just add the characters to the [special characters vec](https://github.com/Edu4rdSHL/findomain/blob/be6ba4f3b30a9bdb0ed4e7d8e6e79a6095a10e0b/src/misc.rs#L9-L14) and that should fix the issue until there appears a new one.
