### ISSUE TITLE
Slack Monitoring Not Working Properly

### ISSUE THREAD

**Issue by amiralkizaru** [Edu4rdSHL/findomain#96]
## Summary

First of all thank you for the awesome tool <3
I have a made a script for subdomain monitoring in slack that looks like this
![carbon(3)](https://user-images.githubusercontent.com/32225186/80794612-df382300-8b89-11ea-9c0c-744c54bd8406.png)

## Expected Behavior

Send results to `Slack` and `Postgres` 

## Actual Behavior

Send Result to `Postgres` only

## Config

`Linux ip-172-31-24-205 4.15.0-1065-aws #69-Ubuntu SMP Thu Mar 26 02:17:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
`findomain 1.5.0`

**Comment by Edu4rdSHL** [comment]
Hello. If the tool commit the data to Postgresql is because the message was sent successfully to Slack, the tool validates that in first place https://github.com/Edu4rdSHL/findomain/blob/57e2df09d0814e7dba3e213fb44f6aa2f0ba2027/src/lib.rs#L390

Can you please execute the tool from your command line directly and see if any error message related to webhooks appears?

Also, can you try `curl -X POST -H 'Content-type: application/json' --data '{"text":"Testing the webhook!"}' YOUR_WEBHOOK_URL` and see if this works?

**Comment by amiralkizaru** [comment]
Hello

Thank you for coming back to me 
For the slack curl command it works fine . I tried it before making the script
![webhook](https://user-images.githubusercontent.com/32225186/80816249-b1210600-8bbe-11ea-85f4-e0f33d55b238.JPG)

And for the tool there is no error when it's executed
Here:
![herer](https://user-images.githubusercontent.com/32225186/80816473-1bd24180-8bbf-11ea-8ec3-0e08fc19aaa9.JPG)

**Comment by Edu4rdSHL** [comment]
That's because there aren't new subdomains for that target. Please can you try with another target? One that you haven't scanned previously, that will give you a message.

**Comment by amiralkizaru** [comment]
Oh yes you're right it works now
Thank you
